private_attribute_callable:
  settings:
    batch_size: 64
    index: 1
    n_collaborators: 2
    test_dataset: src.collaborator_private_attrs.test_dataset
    train_dataset: src.collaborator_private_attrs.train_dataset
  template: src.collaborator_private_attrs.collaborator_private_attrs