settings:
  listen_host: localhost
  listen_port: 50050
  envoy_health_check_period: 5  # in seconds

private_attribute_callable:
  settings:
    batch_size: 50
    watermark_data: src.aggregator_private_attrs.watermark_data
  template: src.aggregator_private_attrs.aggregator_private_attrs